### ISSUE TITLE
[Domai.nr] API key required

### ISSUE THREAD

**Issue by rakiru** [UltrosBot/Ultros-contrib#29]
An API key is now required to use the domainr API. There's also a v2 API, but the old one should continue to work, so no big deal there (see #28).

`{u'message': u'unauthorized: invalid API client ID'}`

**Comment by rakiru** [comment]
Actually, this broke /because/ of #28. I forgot I updated all my plugins, which pulled down the now-broken version. Still, an API key will be needed moving forward. I would like to revert that PR in the mean time though.

**Comment by gdude2002** [comment]
Given that we were told the client ID was optional I thought it wouldn't break it in the meantime - reverting might be best until we have API keys

**Comment by rakiru** [comment]
Oops, I left this off a bit long. I'll get to it now.

@case Do you still want a `client_id` sent along with the API key? I'm not sure if you use them for statistics or anything.

**Comment by gdude2002** [comment]
@case Respectfully, I'm having issues with using Mashape for this given the number of navigational bugs on the site and the demand for a credit card for use with a "free tier". In this day and age, handing out your credit card details to random sites is a bad idea at best, and I don't feel that Mashape is trustworthy enough.

As much as I love Domainr and the services it provides, this is an open source project provided at zero cost to everyone, and due to my personal circumstances, I can't afford to go plugging my CC details into sites that.. Seem to require payment details for free tiers for some reason. Is there any possible alternative to this, or are we going to have to drop support?

**Comment by rakiru** [comment]
Just to add to what g has said, it's perfectly reasonable having a rate limit on a free tier, but having to enter payment details to access that free tier is quite the hurdle. Not all of our users are even in a position where they can provide such a thing. I'm also not sure if Mashape allows you to set limits, in which case I really wouldn't trust it with those details (and my limit would be $0 as I would personally only hit that many requests by accident, and it wouldn't need my details in that case anyway).

**Comment by case** [comment]
@rakiru yes, unfortunately a credit card is required to use the API via Mashape, even for the free tier. Presumably this is to curb abuse. (I asked them about this when we moved our self-serve API to their platform).

**Comment by rakiru** [comment]
Well, in that case, I guess I'll remove this plugin. Thanks for the API up to now, and good luck with it in future.

**Comment by case** [comment]
Thought of an alternative. We're fans and supporters of all things open source and developer tinkering, which definitely applies to you here. Email us at `partners@domainr.com` and we'll provide a `client_id` for your private, hobby-level use. As long as it doesn't get abused or shared broadly, you can keep using it for free. Ideally your query volume would stay within the free tier level listed on Mashape.

What we're trying to curb is the severe, high-volume abuse that inevitably happens when people find API keys floating around Github.

**Comment by gdude2002** [comment]
How does this solve the problem for our users? Won't they still need keys/IDs? 

While I understand that concern, I feel like API keys can be somewhat over the top for the readonly sections of an API. That said, I also understand protecting against competitors from using it for scraping, so it seems understandable from that aspect. 

Honestly, the only problem I really have with Mashape at this point is the credit card requirement - it just appears sketchy as it makes the system appear like a money grab, similar to what you see with American mobile operators - go over your data cap and you'll be charged infinitely. I totally agree with limiting APIs, and it makes a lot of sense, but a limit should be a hard limit in my opinion - I'd want it to stop working when I hit it. 

Maybe I'm crazy, I don't know. Either way, I have no issues with an API requiring a key or being limited, and no issues telling our users to go get a key - Mashape just doesn't seem trustworthy. Your API itself is fine.

**Comment by rakiru** [comment]
I completely understand the move to API keys, and personally think it was a good move. The main problem is the credit card requirement.

Mashape does allow you to set limits, but when that limit is $0.00, they shouldn't need my info in the first place. If does little to stop abuse as you could simply pick up a bunch of prepaid cards.

We appreciate that this is a free API, and you still provide great support[1]. A `client_id` would be appreciated, as that would allow me to still develop the plugin for anyone else that doesn't have an issue with handing out their payment info left, right and centre. I have already updated the plugin to use an API key and/or `client_id` based on a config.

I'm not entirely sure if I want a plugin here that is of use to such a small number of people, but I guess that's kind of the point of contrib, and we have that WoW one, so hey, why not.

[1] Which is why I recommend you any chance I get. I wish I had an actual use for the API where I could pay for it.

**Comment by case** [comment]
@gdude2002, yep your users can hit us up for keys too. You're welcome to mention this in your project documentation, if you'd like.

Re: "just error when the quota is hit," you're not crazy :) — I expected this as well, and was surprised that Mashape didn't offer this functionality. Product-wise I think they opted for, "don't disrupt a service, and track + bill for overages" instead. I definitely see the pros and cons for both approaches, and unfortunately this is what they currently offer.

@rakiru I suspect the free-tier card requirement is to prevent people from just making multiple accounts. It's definitely effective, albeit overkill.

I appreciate you all taking the time to explain your angle on this, as well as listening to ours. We're using Mashape as a self-serve billing proxy due to our own development-resource scarcity, and I really wish they offered more flexibility here.

**Comment by gdude2002** [comment]
@case Wait, you're okay with us telling them to email you guys? Can you clarify that? :P

I guess I can understand the multiple accounts thing.. Well, assuming they have some way to detect all kinds of prepaid cards. But if it works for them, I guess.

Yeah, I can understand needing something like this when you're short of staff or resources; I guess you've gotta take what you can get, right?

**Comment by rakiru** [comment]
@case Thanks a lot for this. I'm not sure what else there is to say without repeating things, but this is why I've been mentioning your service to anyone I can. It's a shame you have to manually deal with that, but I guess that's a small price to pay to avoid abuse, and I've yet to find a service on par with domainr. Thanks again.

**Comment by case** [comment]
@gdude2002 apologies for the delay here. Yes, if folks write into us explaining their ask, we'd request that they agree to hobby / developer-tier usage, aligning with the Mashape [query volume limits].

**Comment by gdude2002** [comment]
@case Awesome, that's pretty fantastic of you guys. Thanks for that - I'll put it in the docs when we get things sorted out.

**Comment by gdude2002** [comment]
@case We did send an email but didn't get a response - Did you guys receive our email, or is there a problem with our own mail configuration?

![](http://vurl.com/qx53D)

**Comment by case** [comment]
Hmm, this is bizarre. I just checked the Google Apps email log search tool, and it doesn't appear:

![](http://f.cl.ly/items/163T0F2Z0L362o1D3C1C/Image%202015-10-03%20at%2009.41.33.png)

I just emailed you a `client_id` to use.

**Comment by gdude2002** [comment]
Well, that's pretty weird. I'll see if I can fix the damn thing. Outlook domain email is a pain in the ass.

Thanks, I've got it. We'll hopefully get this done soon.
